export const Users = [
  {
    id: 1,
    profilepic: "assets/profilevector.jpg",
    time: 15,
    username: "Ismail Draoui",
  },
  {
    id: 2,
    profilepic: "assets/profilevector.jpg",
    time: 4,
    username: "John Doe",
  },
  {
    id: 3,
    profilepic: "assets/profilevector.jpg",
    time: 20,
    username: "Matt Smith",
  },
  {
    id: 4,
    profilepic: "assets/profilevector.jpg",
    time: 45,
    username: "Ron Giligan",
  },
  {
    id: 5,
    profilepic: "assets/profilevector.jpg",
    time: 3,
    username: "Ma mamia",
  },
  {
    id: 6,
    profilepic: "assets/profilevector.jpg",
    time: 15,
    username: "red sparrow",
  },
  {
    id: 7,
    profilepic: "assets/profilevector.jpg",
    time: 4,
    username: "dito rinieri",
  },
  {
    id: 8,
    profilepic: "assets/profilevector.jpg",
    time: 20,
    username: "morekto lafinta",
  },
  {
    id: 9,
    profilepic: "assets/profilevector.jpg",
    time: 45,
    username: "Ronaldo rito",
  },
  {
    id: 10,
    profilepic: "assets/profilevector.jpg",
    time: 3,
    username: "Mike roth",
  },
];
export const Posts = [
  {
    id: 1,
    photo: "assets/friends_img.jpg",
    date: "",
    userId: 1,
    like: 8,
    comment: 23,
  },
  {
    id: 2,
    photo: "assets/friends_img.jpg",
    date: "",
    userId: 2,
    like: 5,
    comment: 6,
  },
  {
    id: 3,
    photo: "assets/friends_img.jpg",
    date: "",
    userId: 3,
    like: 15,
    comment: 10,
  },
  {
    id: 4,
    photo: "assets/friends_img.jpg",
    date: "",
    userId: 4,
    like: 65,
    comment: 6,
  },
  {
    id: 5,
    photo: "assets/friends_img.jpg",
    date: "",
    userId: 5,
    like: 7,
    comment: 2,
  },
  {
    id: 6,
    photo: "assets/friends_img.jpg",
    date: "",
    userId: 6,
    like: 8,
    comment: 7,
  },
];
