export const Users = [
  {
    id: 1,
    profilepic: './public/assets/profilevector.jpg',
    time: 15,
    username: 'Ismail Draoui',
    isAdmin: true,
    email: 'sma1@sma.com',
    password: 'abc123',
  },
  {
    id: 2,
    profilepic: 'assets/profilevector.jpg',
    time: 4,
    username: 'John Doe',
    isAdmin: false,
    email: 'sma2@sma.com',
    password: 'abc123',
  },
  {
    id: 3,
    profilepic: 'assets/profilevector.jpg',
    time: 20,
    username: 'Matt Smith',
    isAdmin: false,
    email: 'sma3@sma.com',
    password: 'abc123',
  },
  {
    id: 4,
    profilepic: 'assets/profilevector.jpg',
    time: 45,
    username: 'Ron Giligan',
    isAdmin: false,
    email: 'sma4@sma.com',
    password: 'abc123',
  },
  {
    id: 5,
    profilepic: 'assets/profilevector.jpg',
    time: 3,
    username: 'Ma mamia',
    isAdmin: false,
    email: 'sma5@sma.com',
    password: 'abc123',
  },
  {
    id: 6,
    profilepic: 'assets/profilevector.jpg',
    time: 15,
    username: 'red sparrow',
    isAdmin: false,
    email: 'sma6@sma.com',
    password: 'abc123',
  },
  {
    id: 7,
    profilepic: 'assets/profilevector.jpg',
    time: 4,
    username: 'dito rinieri',
    isAdmin: false,
    email: 'sma7@sma.com',
    password: 'abc123',
  },
  {
    id: 8,
    profilepic: 'assets/profilevector.jpg',
    time: 20,
    username: 'morekto lafinta',
    isAdmin: false,
    email: 'sma8@sma.com',
    password: 'abc123',
  },
  {
    id: 9,
    profilepic: 'assets/profilevector.jpg',
    time: 45,
    username: 'Ronaldo rito',
    isAdmin: false,
    email: 'sma9@sma.com',
    password: 'abc123',
  },
  {
    id: 10,
    profilepic: 'assets/profilevector.jpg',
    time: 3,
    username: 'Mike roth',
    isAdmin: false,
    email: 'sma10@sma.com',
    password: 'abc123',
  },
];
export const Posts = [
  {
    id: 1,
    photo: 'assets/friends_img.jpg',
    date: '',
    userId: 1,
    like: 8,
    comment: 23,
  },
  {
    id: 2,
    photo: 'assets/friends_img.jpg',
    date: '',
    userId: 2,
    like: 5,
    comment: 6,
  },
  {
    id: 3,
    photo: 'assets/friends_img.jpg',
    date: '',
    userId: 3,
    like: 15,
    comment: 10,
  },
  {
    id: 4,
    photo: 'assets/friends_img.jpg',
    date: '',
    userId: 4,
    like: 65,
    comment: 6,
  },
  {
    id: 5,
    photo: 'assets/friends_img.jpg',
    date: '',
    userId: 5,
    like: 7,
    comment: 2,
  },
  {
    id: 6,
    photo: 'assets/friends_img.jpg',
    date: '',
    userId: 6,
    like: 8,
    comment: 7,
  },
];
